# GNU Makefile

default: algoritmo-servidor-central

algoritmo-servidor-central: Algoritmo-do-Servidor-Central/Makefile
	cd Algoritmo-do-Servidor-Central && make
	@echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
	@echo "Algoritmo-do-Servidor-Central: OK"
	@echo "-------------------------------------"

clean:
	cd Algoritmo-do-Servidor-Central  && make clean
